import { useEffect, useState } from 'react';
import { ArrowRight, CalendarDays, Camera, ChevronRight, Clock3, MapPin, Menu, MessageCircle, Scissors, ShieldCheck, Sparkles, Star, X } from 'lucide-react';
import { BUSINESS, whatsappLink } from './config/business';

const A = ({children, service, className = 'button dark'}:{children:React.ReactNode; service?:string; className?:string}) => <a className={className} href={whatsappLink(service)} target="_blank" rel="noreferrer">{children}<ArrowRight size={16}/></a>;
const SectionTitle=({eyebrow,title,copy}:{eyebrow:string;title:string;copy?:string})=><div className="section-title"><p className="eyebrow">{eyebrow}</p><h2>{title}</h2>{copy&&<p className="copy">{copy}</p>}</div>;
const images=[
  'https://images.unsplash.com/photo-1525507119028-ed4c629a60a3?auto=format&fit=crop&w=900&q=85','https://images.unsplash.com/photo-1596704017254-9b121068fb31?auto=format&fit=crop&w=700&q=85','https://images.unsplash.com/photo-1515377905703-c4788e51af15?auto=format&fit=crop&w=700&q=85','https://images.unsplash.com/photo-1560066984-138dadb4c035?auto=format&fit=crop&w=900&q=85','https://images.unsplash.com/photo-1600948836101-f9ffda59d250?auto=format&fit=crop&w=700&q=85','https://images.unsplash.com/photo-1595476108010-b4d1f102b1b1?auto=format&fit=crop&w=700&q=85'];

export default function App(){
 const [open,setOpen]=useState(false),[scrolled,setScrolled]=useState(false);
 useEffect(()=>{const f=()=>setScrolled(scrollY>30); addEventListener('scroll',f); return()=>removeEventListener('scroll',f)},[]);
 const nav=['Início','Serviços','Sobre','Equipe','Galeria','Avaliações','Contato'];
 return <><header className={scrolled?'header scrolled':'header'}><a className="logo" href="#inicio"><span>STUDIO</span>BELLA</a><nav>{nav.map(x=><a href={'#'+x.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase()} key={x}>{x}</a>)}</nav><A className="button header-cta"><CalendarDays size={16}/>Agendar horário</A><button className="menu" onClick={()=>setOpen(!open)} aria-label="Abrir menu">{open?<X/>:<Menu/>}</button></header>
 {open&&<div className="mobile-nav">{nav.map(x=><a onClick={()=>setOpen(false)} href={'#'+x.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase()} key={x}>{x}</a>)}<A>Agendar horário</A></div>}
 <main>
 <section id="inicio" className="hero"><img src="https://images.unsplash.com/photo-1560066984-138dadb4c035?auto=format&fit=crop&w=2000&q=90" alt="Interior elegante do Studio Bella"/><div className="hero-shade"/><div className="hero-content"><p className="eyebrow light">Sua beleza, seu momento</p><h1>BELEZA QUE<br/><i>VALORIZA</i> QUEM VOCÊ É.</h1><p>Um espaço pensado para você se sentir ainda mais bonita, confiante e especial.</p><div className="actions"><A>Agendar pelo WhatsApp</A><a className="text-link" href="#servicos">Conhecer serviços <ChevronRight size={17}/></a></div></div><div className="hero-notes"><span>Atendimento personalizado</span><span>Profissionais especializados</span><span>Ambiente exclusivo</span></div></section>
 <section id="servicos" className="section services"><SectionTitle eyebrow="Nossos serviços" title="BELEZA DO SEU JEITO" copy="Cuidados pensados para valorizar sua beleza e proporcionar uma experiência especial em cada visita."/><div className="service-grid">{BUSINESS.services.map(s=><article className="service-card" key={s.name}><img src={s.image} alt={s.name} loading="lazy"/><div><h3>{s.name}</h3><p>{s.description}</p><div className="card-bottom"><strong>{s.price}</strong><a href={whatsappLink(s.name)} target="_blank" rel="noreferrer" aria-label={'Agendar '+s.name}><ArrowRight size={19}/></a></div></div></article>)}</div></section>
 <section className="values"><div><Sparkles/><h3>Atendimento<br/>personalizado</h3><p>Escuta e cuidado em cada detalhe.</p></div><div><Scissors/><h3>Profissionais<br/>especializados</h3><p>Técnica, repertório e paixão pelo que fazem.</p></div><div><ShieldCheck/><h3>Produtos de<br/>alta qualidade</h3><p>Marcas selecionadas para você.</p></div><div><Star/><h3>Ambiente<br/>exclusivo</h3><p>Seu momento de pausa e bem-estar.</p></div></section>
 <section id="sobre" className="section about"><div className="about-image"><img src="https://images.unsplash.com/photo-1562322140-8baeececf3df?auto=format&fit=crop&w=1200&q=85" alt="Profissional realizando atendimento no salão" loading="lazy"/><span>Desde 2021</span></div><div className="about-copy"><p className="eyebrow">O Studio Bella</p><h2>MAIS QUE UM SALÃO.<br/><i>UM MOMENTO</i> PARA VOCÊ.</h2><p>No Studio Bella, acreditamos que cuidar da beleza também é cuidar de si. Nosso espaço foi criado para oferecer uma experiência confortável, personalizada e especial em cada visita.</p><div className="stats">{BUSINESS.stats.map(x=><div key={x.label}><b>{x.number}</b><span>{x.label}</span></div>)}</div><a className="text-link dark-link" href="#equipe">Conheça nossa equipe <ArrowRight size={17}/></a></div></section>
 <section id="equipe" className="section team"><SectionTitle eyebrow="Nosso time" title="QUEM CUIDA DE VOCÊ"/><div className="team-grid">{BUSINESS.team.map((p,i)=><article key={p.name} className="team-card"><img src={p.image} alt={p.name} loading="lazy"/><div><span>0{i+1}</span><h3>{p.name}</h3><p>{p.role}</p></div></article>)}</div></section>
 <section id="galeria" className="section gallery"><SectionTitle eyebrow="Inspiração" title="PEQUENOS DETALHES, GRANDES MOMENTOS"/><div className="masonry">{images.map((im,i)=><img key={im} src={im} alt="Resultado e ambiente Studio Bella" loading="lazy" className={'m'+i}/>)}</div></section>
 <section id="avaliações" className="reviews"><div className="review-head"><SectionTitle eyebrow="Avaliações" title="QUEM VIVE ESSA EXPERIÊNCIA, VOLTA"/><A>Agendar pelo WhatsApp</A></div><div className="reviews-grid">{BUSINESS.testimonials.map(t=><blockquote key={t.name}><div className="stars">★★★★★</div><p>“{t.text}”</p><footer>— {t.name}</footer></blockquote>)}</div></section>
 <section className="instagram"><div><p className="eyebrow light">Instagram</p><h2>ACOMPANHE<br/>NOSSO TRABALHO</h2><p>Veja nossos últimos trabalhos e novidades no Instagram.</p><a className="button champagne" href={BUSINESS.instagramUrl} target="_blank" rel="noreferrer"><Camera size={17}/>{BUSINESS.instagram}</a></div><div className="insta-grid">{images.slice(0,4).map(x=><img src={x} key={x} alt="Trabalho do Studio Bella" loading="lazy"/>)}</div></section>
 <section id="contato" className="section visit"><SectionTitle eyebrow="Contato" title="VENHA NOS VISITAR"/><div className="visit-grid"><div className="map"><div><MapPin size={32}/><p>Studio Bella</p><span>{BUSINESS.address}</span></div></div><div className="contact-info"><div><MapPin/><p><b>Endereço</b>{BUSINESS.address}</p></div><div><Clock3/><p><b>Horários</b>{BUSINESS.hours.map(h=><span key={h}>{h}</span>)}</p></div><div><MessageCircle/><p><b>Telefone</b>{BUSINESS.phone}</p></div><div className="contact-actions"><a className="button outline" target="_blank" rel="noreferrer" href="https://maps.google.com/?q=Av.+Getúlio+Vargas,+1250">Como chegar <ArrowRight size={16}/></a><A>WhatsApp</A></div></div></div></section>
 <section className="final"><p className="eyebrow light">Seu tempo é precioso</p><h2>SEU PRÓXIMO MOMENTO DE<br/><i>BELEZA</i> COMEÇA AQUI.</h2><p>Agende seu horário e venha viver uma experiência diferente.</p><A>Agendar pelo WhatsApp</A></section>
 </main><a className="float-whats" href={whatsappLink()} target="_blank" rel="noreferrer" aria-label="Agendar pelo WhatsApp"><MessageCircle/></a><footer className="footer"><a className="logo" href="#inicio"><span>STUDIO</span>BELLA</a><p>{BUSINESS.address}</p><div><a href={BUSINESS.instagramUrl}>Instagram</a><a href={whatsappLink()}>WhatsApp</a></div><small>© 2026 Studio Bella. Todos os direitos reservados.</small></footer></>
}
